describe('#13843 EduPlusOnline', () => {
  it('Zdalne wypełnianie formularzy', () => {
    cy.visit('https://klient.interrisk.pl/EduPlusOnline')
    cy.get('#MainContent_cphMainContent_ucClientVerification_tbClientNumber')
      .focus()
      .type('6p6ny')
      .should('have.value', '6p6ny')
    cy.get('#MainContent_cphMainContent_ucClientVerification_btnSearch')
      .click({ force: true })
    cy.get('#MainContent_cphMainContent_uxPersonalDataAgreement')
      .click()
    cy.get('#MainContent_cphMainContent_uxOdpowiedzialniPlDeclaration1_cbStatementAgreement')
      .click()
    cy.get('#MainContent_cphMainContent_uxOdpowiedzialniPlDeclaration2_cbStatementAgreement')
      .click()
    cy.get('#MainContent_cphMainContent_uxOdpowiedzialniPlDeclaration3_cbStatementAgreement')
      .click()
    cy.get('#MainContent_cphMainContent_uxOdpowiedzialniPlDeclaration4_cbStatementAgreement')
      .click()
    cy.get('#MainContent_cphMainContent_ucVirtualOfferVariants_lvPolicyOfferVariants_VariantFooter_21_ucIssueVariant2_21_btnIssueWithoutSport_21')
      .click()
    cy.get('#MainContent_cphMainContent_ucDeclarantData_tbFirstName')
      .type('tester')
      .blur()
      .should('have.value', 'TESTER')
    cy.get('#MainContent_cphMainContent_ucDeclarantData_tbLastName')
      .type('testowy')
      .blur()
      .should('have.value', 'TESTOWY')
    cy.get('#MainContent_cphMainContent_ucDeclarantData_tbPesel')
      .type('36020535031')
      .should('have.value', '36020535031')
    cy.get('#MainContent_cphMainContent_ucDeclarantData_tbEmail')
      .type('test@biu.pl')
      .blur()
      .should('have.value', 'TEST@BIU.PL')
    cy.get('#MainContent_cphMainContent_ucDeclarantData_tbEmailRepeat')
      .type('test@biu.pl')
      .blur()
      .should('have.value', 'TEST@BIU.PL')
    cy.get('#MainContent_cphMainContent_ucInsuredData_btnCopyFromDeclarant')
      .click()
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbFirstName')
      .should('have.value', 'TESTER')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbLastName')
      .should('have.value', 'TESTOWY')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbPesel')
      .should('have.value', '36020535031')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbPostalCode')
      .focus()
      .type('80222')
      .blur()
      .should('have.value', '80-222')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbPostalCity')
      .should('have.value', 'GDAŃSK')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbCity')
      .type('gdańsk')
      .blur()
      .should('have.value', 'GDAŃSK')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbStreet')
      .type('morska')
      .blur()
      .should('have.value', 'MORSKA')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbBuildingNumber')
      .type('1')
      .blur()
      .should('have.value', '1')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbFlatNumber')
      .type('2')
      .blur()
      .should('have.value', '2')
    cy.get('#MainContent_cphMainContent_ucInsuredData_tbInstitution')
      .type('sp55')
      .blur()
      .should('have.value', 'SP55')
    cy.get('#MainContent_cphMainContent_ucInsuredData_btnInsuredAdd')
      .click()
    cy.get('tbody > tr > :nth-child(2)')
      .should('contain', 'TESTER TESTOWY')
    cy.get('tbody > tr > :nth-child(3)')
      .should('contain', '36020535031')
    cy.get('tbody > tr > :nth-child(4)')
      .should('contain', 'UL. MORSKA 1 / 2 , 80-222 GDAŃSK')
    cy.get('#MainContent_cphMainContent_btnGoToSummary')
      .click()
    cy.server()
    cy.route('POST', 'https://klient.interrisk.pl/EduPlusOnline').as('redirectToPayU')
    cy.get('#MainContent_cphMainContent_btnGoToPayment')
      .click()
    cy.wait('@redirectToPayU').then((xhr) => {
      expect(xhr.response.body).to.contain('payu.com')
    })
  })
})
